---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: alpine
    commands:
      - apk add rust nodejs make curl unzip
      - curl https://github.com/hakimel/reveal.js/archive/master.zip -VL -o master.zip
      - make
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/doffice.git
