---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: alpine
    commands:
      - apk add rustup nodejs make curl unzip
      - rustup install latest
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/doffice.git
