---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: rust
    commands:
      - apt update; apt install -y nodejs npm
      - rustup update nightly; rustup default nightly
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/doffice.git
