---
kind: pipeline
type: docker
name: build

steps:
  - name: build and test
    image: rust:unstable
    commands:
      - apt update; apt install -y nodejs make curl unzip npm
      - rustup update nightly; rustup default nightly
      - make
      - cargo build
      - cargo test

  - template: github-mirror
    repo: git@github.com:DSchroer/doffice.git
